# Generated by Django 4.2.7 on 2023-11-19 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parimal_ingle_CMA', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='created_time',
        ),
    ]
