# Generated by Django 4.2.7 on 2023-11-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parimal_ingle_CMA', '0002_remove_contacts_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='created_time',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
